name: Deploy Frontend App to Cloud Run

on:
  push:
    paths:
      - 'service/app/**'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build & Push Docker Image
        run: |
          gcloud builds submit ./service/app \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/template-project-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy template-project-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/template-project-app \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated